export const TOKOPUYO_SUGGESTION_CONFIG = Object.freeze({
  visibleHands: 2,
  depth: 16,
  width: 250,
  branchCount: 6,
  workerCount: 3,
  lookaheadHands: 3,
  resultLimit: 4,
  beamWidth: 240,
  timeBudgetMs: 8_000,
  visibleSearchRatio: 0.72,
  maximumConstructionHeight: 11,
  safetyCandidateLimit: 10,
  allowEmergencyClearFallback: true,
});
